level4: CWE-122.c CWE-244.c CWE-415.c CWE-416.c
	gcc -o CWE-122 -m32 CWE-122.c
	gcc -o CWE-244 -m32 CWE-244.c
	gcc -o CWE-415 -m32 CWE-415.c
	gcc -o CWE-416 -m32 CWE-416.c

clean:
	rm -f CWE-122
	rm -f CWE-244
	rm -f CWE-415
	rm -f CWE-416
