level1: CWE-128.c CWE-134.c CWE-191.c CWE-194.c CWE-242.c CWE-476.c
	gcc -o CWE-128 CWE-128.c
	gcc -o CWE-134 CWE-134.c -Wno-format-security
	gcc -o CWE-191 CWE-191.c
	gcc -o CWE-194 CWE-194.c
	gcc -o CWE-242 CWE-242.c -Wno-implicit
	gcc -o CWE-476 CWE-476.c

clean:
	rm -f CWE-128
	rm -f CWE-134
	rm -f CWE-191
	rm -f CWE-194
	rm -f CWE-242
	rm -f CWE-476
