level1: CWE-457.c CWE-478.c CWE-480.c CWE-483.c CWE-484.c CWE-783.c
	gcc -o CWE-457 CWE-457.c
	gcc -o CWE-478 CWE-478.c
	gcc -o CWE-480 CWE-480.c
	gcc -o CWE-483 CWE-483.c
	gcc -o CWE-484 CWE-484.c
	gcc -o CWE-783 CWE-783.c

clean:
	rm -f CWE-457
	rm -f CWE-478
	rm -f CWE-480
	rm -f CWE-483
	rm -f CWE-484
	rm -f CWE-783
