level5: ls_vuln.c wc_vuln.c strings_vuln.c which_vuln.c rev_vuln.c
	gcc -o ls_vuln -m32 ls_vuln.c
	gcc -o wc_vuln -m32 wc_vuln.c
	gcc -o strings_vuln -m32 strings_vuln.c
	gcc -o which_vuln -m32 which_vuln.c
	gcc -o rev_vuln -m32 rev_vuln.c

clean:
	rm -f ls_vuln
	rm -f wc_vuln
	rm -f strings_vuln
	rm -f which_vuln
	rm -f rev_vuln
