level3: CWE-121.c CWE-124.c CWE-126.c CWE-127.c CWE-170.c
	gcc -o CWE-121 -m32 CWE-121.c -fno-stack-protector
	gcc -o CWE-124 -m32 CWE-124.c -fno-stack-protector
	gcc -o CWE-126 -m32 CWE-126.c -fno-stack-protector
	gcc -o CWE-127 -m32 CWE-127.c -fno-stack-protector
	gcc -o CWE-170 -m32 CWE-170.c -fno-stack-protector

clean:
	rm -f CWE-121
	rm -f CWE-124
	rm -f CWE-126
	rm -f CWE-127
	rm -f CWE-170
