level1: CWE-124.c CWE-127.c CWE-170.c
	gcc -o CWE-124 CWE-124.c
	gcc -o CWE-127 CWE-127.c -fno-stack-protector
	gcc -o CWE-170 CWE-170.c -fno-stack-protector

clean:
	rm -f CWE-124
	rm -f CWE-127
	rm -f CWE-170
